package com.pippsford.beantester.factories.basic;

import java.util.random.RandomGenerator;

import com.pippsford.beantester.TestContext;
import com.pippsford.beantester.ValueFactory;

/** A class that creates phrases from the PGP word list. */
class PgpWordsValueFactory extends ValueFactory {

  /** List of the PGP words. */
  private static final String[][] WORDS = new String[][]{
      {"Aardvark", "Adroitness"},
      {"Absurd", "Adviser"},
      {"Accrue", "Aftermath"},
      {"Acme", "Aggregate"},
      {"Adrift", "Alkali"},
      {"Adult", "Almighty"},
      {"Afflict", "Amulet"},
      {"Ahead", "Amusement"},
      {"Aimless", "Antenna"},
      {"Algol", "Applicant"},
      {"Allow", "Apollo"},
      {"Alone", "Armistice"},
      {"Ammo", "Article"},
      {"Ancient", "Asteroid"},
      {"Apple", "Atlantic"},
      {"Artist", "Atmosphere"},
      {"Assume", "Autopsy"},
      {"Athens", "Babylon"},
      {"Atlas", "Backwater"},
      {"Aztec", "Barbecue"},
      {"Baboon", "Belowground"},
      {"Backfield", "Bifocals"},
      {"Backward", "Bodyguard"},
      {"Banjo", "Bookseller"},
      {"Beaming", "Borderline"},
      {"Bedlamp", "Bottomless"},
      {"Beehive", "Bradbury"},
      {"Beeswax", "Bravado"},
      {"Befriend", "Brazilian"},
      {"Belfast", "Breakaway"},
      {"Berserk", "Burlington"},
      {"Billiard", "Businessman"},
      {"Bison", "Butterfat"},
      {"Blackjack", "Camelot"},
      {"Blockade", "Candidate"},
      {"Blowtorch", "Cannonball"},
      {"Bluebird", "Capricorn"},
      {"Bombast", "Caravan"},
      {"Bookshelf", "Caretaker"},
      {"Brackish", "Celebrate"},
      {"Breadline", "Cellulose"},
      {"Breakup", "Certify"},
      {"Brickyard", "Chambermaid"},
      {"Briefcase", "Cherokee"},
      {"Burbank", "Chicago"},
      {"Button", "Clergyman"},
      {"Buzzard", "Coherence"},
      {"Cement", "Combustion"},
      {"Chairlift", "Commando"},
      {"Chatter", "Company"},
      {"Checkup", "Component"},
      {"Chisel", "Concurrent"},
      {"Choking", "Confidence"},
      {"Chopper", "Conformist"},
      {"Christmas", "Congregate"},
      {"Clamshell", "Consensus"},
      {"Classic", "Consulting"},
      {"Classroom", "Corporate"},
      {"Cleanup", "Corrosion"},
      {"Clockwork", "Councilman"},
      {"Cobra", "Crossover"},
      {"Commence", "Crucifix"},
      {"Concert", "Cumbersome"},
      {"Cowbell", "Customer"},
      {"Crackdown", "Dakota"},
      {"Cranky", "Decadence"},
      {"Crowfoot", "December"},
      {"Crucial", "Decimal"},
      {"Crumpled", "Designing"},
      {"Crusade", "Detector"},
      {"Cubic", "Detergent"},
      {"Dashboard", "Determine"},
      {"Deadbolt", "Dictator"},
      {"Deckhand", "Dinosaur"},
      {"Dogsled", "Direction"},
      {"Dragnet", "Disable"},
      {"Drainage", "Disbelief"},
      {"Dreadful", "Disruptive"},
      {"Drifter", "Distortion"},
      {"Dropper", "Document"},
      {"Drumbeat", "Embezzle"},
      {"Drunken", "Enchanting"},
      {"Dupont", "Enrollment"},
      {"Dwelling", "Enterprise"},
      {"Eating", "Equation"},
      {"Edict", "Equipment"},
      {"Egghead", "Escapade"},
      {"Eightball", "Eskimo"},
      {"Endorse", "Everyday"},
      {"Endow", "Examine"},
      {"Enlist", "Existence"},
      {"Erase", "Exodus"},
      {"Escape", "Fascinate"},
      {"Exceed", "Filament"},
      {"Eyeglass", "Finicky"},
      {"Eyetooth", "Forever"},
      {"Facial", "Fortitude"},
      {"Fallout", "Frequency"},
      {"Flagpole", "Gadgetry"},
      {"Flatfoot", "Galveston"},
      {"Flytrap", "Getaway"},
      {"Fracture", "Glossary"},
      {"Framework", "Gossamer"},
      {"Freedom", "Graduate"},
      {"Frighten", "Gravity"},
      {"Gazelle", "Guitarist"},
      {"Geiger", "Hamburger"},
      {"Glitter", "Hamilton"},
      {"Glucose", "Handiwork"},
      {"Goggles", "Hazardous"},
      {"Goldfish", "Headwaters"},
      {"Gremlin", "Hemisphere"},
      {"Guidance", "Hesitate"},
      {"Hamlet", "Hideaway"},
      {"Highchair", "Holiness"},
      {"Hockey", "Hurricane"},
      {"Indoors", "Hydraulic"},
      {"Indulge", "Impartial"},
      {"Inverse", "Impetus"},
      {"Involve", "Inception"},
      {"Island", "Indigo"},
      {"Jawbone", "Inertia"},
      {"Keyboard", "Infancy"},
      {"Kickoff", "Inferno"},
      {"Kiwi", "Informant"},
      {"Klaxon", "Insincere"},
      {"Locale", "Insurgent"},
      {"Lockup", "Integrate"},
      {"Merit", "Intention"},
      {"Minnow", "Inventive"},
      {"Miser", "Istanbul"},
      {"Mohawk", "Jamaica"},
      {"Mural", "Jupiter"},
      {"Music", "Leprosy"},
      {"Necklace", "Letterhead"},
      {"Neptune", "Liberty"},
      {"Newborn", "Maritime"},
      {"Nightbird", "Matchmaker"},
      {"Oakland", "Maverick"},
      {"Obtuse", "Medusa"},
      {"Offload", "Megaton"},
      {"Optic", "Microscope"},
      {"Orca", "Microwave"},
      {"Payday", "Midsummer"},
      {"Peachy", "Millionaire"},
      {"Pheasant", "Miracle"},
      {"Physique", "Misnomer"},
      {"Playhouse", "Molasses"},
      {"Pluto", "Molecule"},
      {"Preclude", "Montana"},
      {"Prefer", "Monument"},
      {"Preshrunk", "Mosquito"},
      {"Printer", "Narrative"},
      {"Prowler", "Nebula"},
      {"Pupil", "Newsletter"},
      {"Puppy", "Norwegian"},
      {"Python", "October"},
      {"Quadrant", "Ohio"},
      {"Quiver", "Onlooker"},
      {"Quota", "Opulent"},
      {"Ragtime", "Orlando"},
      {"Ratchet", "Outfielder"},
      {"Rebirth", "Pacific"},
      {"Reform", "Pandemic"},
      {"Regain", "Pandora"},
      {"Reindeer", "Paperweight"},
      {"Rematch", "Paragon"},
      {"Repay", "Paragraph"},
      {"Retouch", "Paramount"},
      {"Revenge", "Passenger"},
      {"Reward", "Pedigree"},
      {"Rhythm", "Pegasus"},
      {"Ribcage", "Penetrate"},
      {"Ringbolt", "Perceptive"},
      {"Robust", "Performance"},
      {"Rocker", "Pharmacy"},
      {"Ruffled", "Phonetic"},
      {"Sailboat", "Photograph"},
      {"Sawdust", "Pioneer"},
      {"Scallion", "Pocketful"},
      {"Scenic", "Politeness"},
      {"Scorecard", "Positive"},
      {"Scotland", "Potato"},
      {"Seabird", "Processor"},
      {"Select", "Provincial"},
      {"Sentence", "Proximate"},
      {"Shadow", "Puberty"},
      {"Shamrock", "Publisher"},
      {"Showgirl", "Pyramid"},
      {"Skullcap", "Quantity"},
      {"Skydive", "Racketeer"},
      {"Slingshot", "Rebellion"},
      {"Slowdown", "Recipe"},
      {"Snapline", "Recover"},
      {"Snapshot", "Repellent"},
      {"Snowcap", "Replica"},
      {"Snowslide", "Reproduce"},
      {"Solo", "Resistor"},
      {"Southward", "Responsive"},
      {"Soybean", "Retraction"},
      {"Spaniel", "Retrieval"},
      {"Spearhead", "Retrospect"},
      {"Spellbind", "Revenue"},
      {"Spheroid", "Revival"},
      {"Spigot", "Revolver"},
      {"Spindle", "Sandalwood"},
      {"Spyglass", "Sardonic"},
      {"Stagehand", "Saturday"},
      {"Stagnate", "Savagery"},
      {"Stairway", "Scavenger"},
      {"Standard", "Sensation"},
      {"Stapler", "Sociable"},
      {"Steamship", "Souvenir"},
      {"Sterling", "Specialist"},
      {"Stockman", "Speculate"},
      {"Stopwatch", "Stethoscope"},
      {"Stormy", "Stupendous"},
      {"Sugar", "Supportive"},
      {"Surmount", "Surrender"},
      {"Suspense", "Suspicious"},
      {"Sweatband", "Sympathy"},
      {"Swelter", "Tambourine"},
      {"Tactics", "Telephone"},
      {"Talon", "Therapist"},
      {"Tapeworm", "Tobacco"},
      {"Tempest", "Tolerance"},
      {"Tiger", "Tomorrow"},
      {"Tissue", "Torpedo"},
      {"Tonic", "Tradition"},
      {"Topmost", "Travesty"},
      {"Tracker", "Trombonist"},
      {"Transit", "Truncated"},
      {"Trauma", "Typewriter"},
      {"Treadmill", "Ultimate"},
      {"Trojan", "Undaunted"},
      {"Trouble", "Underfoot"},
      {"Tumor", "Unicorn"},
      {"Tunnel", "Unify"},
      {"Tycoon", "Universe"},
      {"Uncut", "Unravel"},
      {"Unearth", "Upcoming"},
      {"Unwind", "Vacancy"},
      {"Uproot", "Vagabond"},
      {"Upset", "Vertigo"},
      {"Upshot", "Virginia"},
      {"Vapor", "Visitor"},
      {"Village", "Vocalist"},
      {"Virus", "Voyager"},
      {"Vulcan", "Warranty"},
      {"Waffle", "Waterloo"},
      {"Wallet", "Whimsical"},
      {"Watchword", "Wichita"},
      {"Wayside", "Wilmington"},
      {"Willow", "Wyoming"},
      {"Woodlark", "Yesteryear"},
      {"Zulu", "Yucatan"}
  };


  /**
   * Create a string from PGP words of the specified length.
   *
   * @param length number of words
   * @param random the random generator to use
   *
   * @return the string
   */
  static String randomWords(int length, RandomGenerator random) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < length; i++) {
      if (i != 0) {
        sb.append(' ');
      }
      int wordIndex = random.nextInt(WORDS.length);
      String[] wordPair = WORDS[wordIndex];
      sb.append(wordPair[i % 2]);
    }
    return sb.toString();
  }


  /**
   * Create a random string from 1 to 4 PGP words.
   *
   * @return the string
   */
  public static String randomWords() {
    RandomGenerator random = TestContext.get().getRandom();
    int length = 1 + random.nextInt(4);
    return randomWords(length, random);
  }


  /**
   * New instance.
   */
  PgpWordsValueFactory() {
    super(String.class, false, () -> WORDS[0][0], () -> WORDS[255][1], PgpWordsValueFactory::randomWords);
  }

}
