// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

/**
 * Protobuf enum {@code beantest.DayOfTheWeek}
 */
public enum DayOfTheWeek
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNSPECIFIED = 0;</code>
   */
  UNSPECIFIED(0),
  /**
   * <code>MONDAY = 1;</code>
   */
  MONDAY(1),
  /**
   * <code>TUESDAY = 2;</code>
   */
  TUESDAY(2),
  /**
   * <code>WEDNESDAY = 3;</code>
   */
  WEDNESDAY(3),
  /**
   * <code>THURSDAY = 4;</code>
   */
  THURSDAY(4),
  /**
   * <code>FRIDAY = 5;</code>
   */
  FRIDAY(5),
  /**
   * <code>SATURDAY = 6;</code>
   */
  SATURDAY(6),
  /**
   * <code>SUNDAY = 7;</code>
   */
  SUNDAY(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FRIDAY = 5;</code>
   */
  public static final int FRIDAY_VALUE = 5;

  /**
   * <code>MONDAY = 1;</code>
   */
  public static final int MONDAY_VALUE = 1;

  /**
   * <code>SATURDAY = 6;</code>
   */
  public static final int SATURDAY_VALUE = 6;

  /**
   * <code>SUNDAY = 7;</code>
   */
  public static final int SUNDAY_VALUE = 7;

  /**
   * <code>THURSDAY = 4;</code>
   */
  public static final int THURSDAY_VALUE = 4;

  /**
   * <code>TUESDAY = 2;</code>
   */
  public static final int TUESDAY_VALUE = 2;

  /**
   * <code>UNSPECIFIED = 0;</code>
   */
  public static final int UNSPECIFIED_VALUE = 0;

  /**
   * <code>WEDNESDAY = 3;</code>
   */
  public static final int WEDNESDAY_VALUE = 3;

  private static final DayOfTheWeek[] VALUES = values();

  private static final com.google.protobuf.Internal.EnumLiteMap<
      DayOfTheWeek> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>() {
        public DayOfTheWeek findValueByNumber(int number) {
          return DayOfTheWeek.forNumber(number);
        }
      };


  /**
   * @param value The numeric wire value of the corresponding enum entry.
   *
   * @return The enum associated with the given numeric wire value.
   */
  public static DayOfTheWeek forNumber(int value) {
    switch (value) {
      case 0:
        return UNSPECIFIED;
      case 1:
        return MONDAY;
      case 2:
        return TUESDAY;
      case 3:
        return WEDNESDAY;
      case 4:
        return THURSDAY;
      case 5:
        return FRIDAY;
      case 6:
        return SATURDAY;
      case 7:
        return SUNDAY;
      default:
        return null;
    }
  }


  public static final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptor() {
    return Example.getDescriptor().getEnumTypes().get(0);
  }


  public static com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>
  internalGetValueMap() {
    return internalValueMap;
  }


  /**
   * @param value The numeric wire value of the corresponding enum entry.
   *
   * @return The enum associated with the given numeric wire value.
   *
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static DayOfTheWeek valueOf(int value) {
    return forNumber(value);
  }


  public static DayOfTheWeek valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc
  ) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;


  private DayOfTheWeek(int value) {
    this.value = value;
  }


  public final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptorForType() {
    return getDescriptor();
  }


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }


  public final com.google.protobuf.Descriptors.EnumValueDescriptor
  getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  // @@protoc_insertion_point(enum_scope:beantest.DayOfTheWeek)
}

