// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

public final class Example {

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_beantest_AllTypes_MapValue2Entry_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beantest_AllTypes_MapValue2Entry_fieldAccessorTable;

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_beantest_AllTypes_MapValueEntry_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beantest_AllTypes_MapValueEntry_fieldAccessorTable;

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_beantest_AllTypes_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beantest_AllTypes_fieldAccessorTable;

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_beantest_MessageWithOneOf_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beantest_MessageWithOneOf_fieldAccessorTable;

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_beantest_NestedMessage_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_beantest_NestedMessage_fieldAccessorTable;

  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;


  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }


  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry
  ) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }


  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry
  ) {
  }

  static {
    String[] descriptorData = {
        "\n\rexample.proto\022\010beantest\"\306\005\n\010AllTypes\022\024" +
            "\n\014double_value\030\001 \001(\001\022\023\n\013float_value\030\002 \001(" +
            "\002\022\023\n\013int32_value\030\003 \001(\005\022\023\n\013int64_value\030\004 " +
            "\001(\003\022\024\n\014uint32_value\030\005 \001(\r\022\024\n\014uint64_valu" +
            "e\030\006 \001(\004\022\024\n\014sint32_value\030\007 \001(\021\022\024\n\014sint64_" +
            "value\030\010 \001(\022\022\025\n\rfixed32_value\030\t \001(\007\022\025\n\rfi" +
            "xed64_value\030\n \001(\006\022\026\n\016sfixed32_value\030\013 \001(" +
            "\017\022\026\n\016sfixed64_value\030\014 \001(\020\022\022\n\nbool_value\030" +
            "\r \001(\010\022\024\n\014string_value\030\016 \001(\t\022\023\n\013bytes_val" +
            "ue\030\017 \001(\014\022/\n\017day_of_the_week\030\020 \001(\0162\026.bean" +
            "test.DayOfTheWeek\0227\n\023message_with_one_of" +
            "\030\021 \001(\0132\032.beantest.MessageWithOneOf\0223\n\tma" +
            "p_value\030\022 \003(\0132 .beantest.AllTypes.MapVal" +
            "ueEntry\0225\n\nmap_value2\030\023 \003(\0132!.beantest.A" +
            "llTypes.MapValue2Entry\022\033\n\023repeated_bool_" +
            "value\030\024 \003(\010\022\032\n\022repeated_int_value\030\025 \003(\005\032" +
            "/\n\rMapValueEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
            " \001(\005:\0028\001\0320\n\016MapValue2Entry\022\013\n\003key\030\001 \001(\005\022" +
            "\r\n\005value\030\002 \001(\t:\0028\001\"]\n\020MessageWithOneOf\022\017" +
            "\n\005label\030\001 \001(\tH\000\022\016\n\004name\030\002 \001(\tH\000\022\016\n\004type\030" +
            "\003 \001(\tH\000\022\016\n\004kind\030\004 \001(\tH\000B\010\n\006nature\"W\n\rNes" +
            "tedMessage\022\r\n\005value\030\001 \001(\005\022,\n\006nested\030\002 \001(" +
            "\0132\027.beantest.NestedMessageH\000\210\001\001B\t\n\007_nest" +
            "ed*{\n\014DayOfTheWeek\022\017\n\013UNSPECIFIED\020\000\022\n\n\006M" +
            "ONDAY\020\001\022\013\n\007TUESDAY\020\002\022\r\n\tWEDNESDAY\020\003\022\014\n\010T" +
            "HURSDAY\020\004\022\n\n\006FRIDAY\020\005\022\014\n\010SATURDAY\020\006\022\n\n\006S" +
            "UNDAY\020\007B%\n!com.pippsford.beantester.prot" +
            "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            }
        );
    internal_static_beantest_AllTypes_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_beantest_AllTypes_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beantest_AllTypes_descriptor,
        new String[]{
            "DoubleValue",
            "FloatValue",
            "Int32Value",
            "Int64Value",
            "Uint32Value",
            "Uint64Value",
            "Sint32Value",
            "Sint64Value",
            "Fixed32Value",
            "Fixed64Value",
            "Sfixed32Value",
            "Sfixed64Value",
            "BoolValue",
            "StringValue",
            "BytesValue",
            "DayOfTheWeek",
            "MessageWithOneOf",
            "MapValue",
            "MapValue2",
            "RepeatedBoolValue",
            "RepeatedIntValue",
        }
    );
    internal_static_beantest_AllTypes_MapValueEntry_descriptor =
        internal_static_beantest_AllTypes_descriptor.getNestedTypes().get(0);
    internal_static_beantest_AllTypes_MapValueEntry_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beantest_AllTypes_MapValueEntry_descriptor,
        new String[]{"Key", "Value",}
    );
    internal_static_beantest_AllTypes_MapValue2Entry_descriptor =
        internal_static_beantest_AllTypes_descriptor.getNestedTypes().get(1);
    internal_static_beantest_AllTypes_MapValue2Entry_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beantest_AllTypes_MapValue2Entry_descriptor,
        new String[]{"Key", "Value",}
    );
    internal_static_beantest_MessageWithOneOf_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_beantest_MessageWithOneOf_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beantest_MessageWithOneOf_descriptor,
        new String[]{"Label", "Name", "Type", "Kind", "Nature",}
    );
    internal_static_beantest_NestedMessage_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_beantest_NestedMessage_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_beantest_NestedMessage_descriptor,
        new String[]{"Value", "Nested", "Nested",}
    );
  }

  private Example() {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
