// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

public interface MessageWithOneOfOrBuilder extends
                                           // @@protoc_insertion_point(interface_extends:beantest.MessageWithOneOf)
                                               com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string kind = 4;</code>
   *
   * @return The kind.
   */
  String getKind();

  /**
   * <code>string kind = 4;</code>
   *
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
  getKindBytes();

  /**
   * <code>string label = 1;</code>
   *
   * @return The label.
   */
  String getLabel();

  /**
   * <code>string label = 1;</code>
   *
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
  getLabelBytes();

  /**
   * <code>string name = 2;</code>
   *
   * @return The name.
   */
  String getName();

  /**
   * <code>string name = 2;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
  getNameBytes();

  MessageWithOneOf.NatureCase getNatureCase();

  /**
   * <code>string type = 3;</code>
   *
   * @return The type.
   */
  String getType();

  /**
   * <code>string type = 3;</code>
   *
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
  getTypeBytes();

  /**
   * <code>string kind = 4;</code>
   *
   * @return Whether the kind field is set.
   */
  boolean hasKind();

  /**
   * <code>string label = 1;</code>
   *
   * @return Whether the label field is set.
   */
  boolean hasLabel();

  /**
   * <code>string name = 2;</code>
   *
   * @return Whether the name field is set.
   */
  boolean hasName();

  /**
   * <code>string type = 3;</code>
   *
   * @return Whether the type field is set.
   */
  boolean hasType();

}
