// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

/**
 * Protobuf type {@code beantest.MessageWithOneOf}
 */
public final class MessageWithOneOf extends
                                    com.google.protobuf.GeneratedMessageV3 implements
                                                                           // @@protoc_insertion_point(message_implements:beantest.MessageWithOneOf)
                                                                               MessageWithOneOfOrBuilder {

  public static final int KIND_FIELD_NUMBER = 4;

  public static final int LABEL_FIELD_NUMBER = 1;

  public static final int NAME_FIELD_NUMBER = 2;

  public static final int TYPE_FIELD_NUMBER = 3;

  // @@protoc_insertion_point(class_scope:beantest.MessageWithOneOf)
  private static final MessageWithOneOf DEFAULT_INSTANCE;

  private static final com.google.protobuf.Parser<MessageWithOneOf>
      PARSER = new com.google.protobuf.AbstractParser<MessageWithOneOf>() {
    @Override
    public MessageWithOneOf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    )
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  private static final long serialVersionUID = 0L;

  public enum NatureCase
      implements com.google.protobuf.Internal.EnumLite,
                 InternalOneOfEnum {
    LABEL(1),
    NAME(2),
    TYPE(3),
    KIND(4),
    NATURE_NOT_SET(0);

    public static NatureCase forNumber(int value) {
      switch (value) {
        case 1:
          return LABEL;
        case 2:
          return NAME;
        case 3:
          return TYPE;
        case 4:
          return KIND;
        case 0:
          return NATURE_NOT_SET;
        default:
          return null;
      }
    }


    /**
     * @param value The number of the enum to look for.
     *
     * @return The enum associated with the given number.
     *
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static NatureCase valueOf(int value) {
      return forNumber(value);
    }

    private final int value;


    private NatureCase(int value) {
      this.value = value;
    }


    public int getNumber() {
      return this.value;
    }
  }



  /**
   * Protobuf type {@code beantest.MessageWithOneOf}
   */
  public static final class Builder extends
                                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                            // @@protoc_insertion_point(builder_implements:beantest.MessageWithOneOf)
                                                                                                MessageWithOneOfOrBuilder {

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Example.internal_static_beantest_MessageWithOneOf_descriptor;
    }

    private int bitField0_;

    private int natureCase_ = 0;

    private Object nature_;


    // Construct using com.pippsford.beantester.protobuf.MessageWithOneOf.newBuilder()
    private Builder() {

    }


    private Builder(
        BuilderParent parent
    ) {
      super(parent);

    }


    @Override
    public MessageWithOneOf build() {
      MessageWithOneOf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }


    @Override
    public MessageWithOneOf buildPartial() {
      MessageWithOneOf result = new MessageWithOneOf(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }


    private void buildPartial0(MessageWithOneOf result) {
      int from_bitField0_ = bitField0_;
    }


    private void buildPartialOneofs(MessageWithOneOf result) {
      result.natureCase_ = natureCase_;
      result.nature_ = this.nature_;
    }


    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      natureCase_ = 0;
      nature_ = null;
      return this;
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      if (natureCase_ == 4) {
        natureCase_ = 0;
        nature_ = null;
        onChanged();
      }
      return this;
    }


    /**
     * <code>string label = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      if (natureCase_ == 1) {
        natureCase_ = 0;
        nature_ = null;
        onChanged();
      }
      return this;
    }


    /**
     * <code>string name = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      if (natureCase_ == 2) {
        natureCase_ = 0;
        nature_ = null;
        onChanged();
      }
      return this;
    }


    public Builder clearNature() {
      natureCase_ = 0;
      nature_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>string type = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearType() {
      if (natureCase_ == 3) {
        natureCase_ = 0;
        nature_ = null;
        onChanged();
      }
      return this;
    }


    @Override
    public MessageWithOneOf getDefaultInstanceForType() {
      return MessageWithOneOf.getDefaultInstance();
    }


    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return Example.internal_static_beantest_MessageWithOneOf_descriptor;
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @return The kind.
     */
    @Override
    public String getKind() {
      Object ref = "";
      if (natureCase_ == 4) {
        ref = nature_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (natureCase_ == 4) {
          nature_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @return The bytes for kind.
     */
    @Override
    public com.google.protobuf.ByteString
    getKindBytes() {
      Object ref = "";
      if (natureCase_ == 4) {
        ref = nature_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (natureCase_ == 4) {
          nature_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }


    /**
     * <code>string label = 1;</code>
     *
     * @return The label.
     */
    @Override
    public String getLabel() {
      Object ref = "";
      if (natureCase_ == 1) {
        ref = nature_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (natureCase_ == 1) {
          nature_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }


    /**
     * <code>string label = 1;</code>
     *
     * @return The bytes for label.
     */
    @Override
    public com.google.protobuf.ByteString
    getLabelBytes() {
      Object ref = "";
      if (natureCase_ == 1) {
        ref = nature_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (natureCase_ == 1) {
          nature_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }


    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = "";
      if (natureCase_ == 2) {
        ref = nature_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (natureCase_ == 2) {
          nature_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }


    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      Object ref = "";
      if (natureCase_ == 2) {
        ref = nature_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (natureCase_ == 2) {
          nature_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }


    public NatureCase
    getNatureCase() {
      return NatureCase.forNumber(
          natureCase_);
    }


    /**
     * <code>string type = 3;</code>
     *
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = "";
      if (natureCase_ == 3) {
        ref = nature_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (natureCase_ == 3) {
          nature_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }


    /**
     * <code>string type = 3;</code>
     *
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
    getTypeBytes() {
      Object ref = "";
      if (natureCase_ == 3) {
        ref = nature_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (natureCase_ == 3) {
          nature_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @return Whether the kind field is set.
     */
    @Override
    public boolean hasKind() {
      return natureCase_ == 4;
    }


    /**
     * <code>string label = 1;</code>
     *
     * @return Whether the label field is set.
     */
    @Override
    public boolean hasLabel() {
      return natureCase_ == 1;
    }


    /**
     * <code>string name = 2;</code>
     *
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return natureCase_ == 2;
    }


    /**
     * <code>string type = 3;</code>
     *
     * @return Whether the type field is set.
     */
    @Override
    public boolean hasType() {
      return natureCase_ == 3;
    }


    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Example.internal_static_beantest_MessageWithOneOf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageWithOneOf.class, Builder.class);
    }


    @Override
    public final boolean isInitialized() {
      return true;
    }


    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MessageWithOneOf) {
        return mergeFrom((MessageWithOneOf) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }


    public Builder mergeFrom(MessageWithOneOf other) {
      if (other == MessageWithOneOf.getDefaultInstance()) {
        return this;
      }
      switch (other.getNatureCase()) {
        case LABEL: {
          natureCase_ = 1;
          nature_ = other.nature_;
          onChanged();
          break;
        }
        case NAME: {
          natureCase_ = 2;
          nature_ = other.nature_;
          onChanged();
          break;
        }
        case TYPE: {
          natureCase_ = 3;
          nature_ = other.nature_;
          onChanged();
          break;
        }
        case KIND: {
          natureCase_ = 4;
          nature_ = other.nature_;
          onChanged();
          break;
        }
        case NATURE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }


    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    )
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              natureCase_ = 1;
              nature_ = s;
              break;
            } // case 10
            case 18: {
              String s = input.readStringRequireUtf8();
              natureCase_ = 2;
              nature_ = s;
              break;
            } // case 18
            case 26: {
              String s = input.readStringRequireUtf8();
              natureCase_ = 3;
              nature_ = s;
              break;
            } // case 26
            case 34: {
              String s = input.readStringRequireUtf8();
              natureCase_ = 4;
              nature_ = s;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }


    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields
    ) {
      return super.mergeUnknownFields(unknownFields);
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @param value The kind to set.
     *
     * @return This builder for chaining.
     */
    public Builder setKind(
        String value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      natureCase_ = 4;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string kind = 4;</code>
     *
     * @param value The bytes for kind to set.
     *
     * @return This builder for chaining.
     */
    public Builder setKindBytes(
        com.google.protobuf.ByteString value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      natureCase_ = 4;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string label = 1;</code>
     *
     * @param value The label to set.
     *
     * @return This builder for chaining.
     */
    public Builder setLabel(
        String value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      natureCase_ = 1;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string label = 1;</code>
     *
     * @param value The bytes for label to set.
     *
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      natureCase_ = 1;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string name = 2;</code>
     *
     * @param value The name to set.
     *
     * @return This builder for chaining.
     */
    public Builder setName(
        String value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      natureCase_ = 2;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string name = 2;</code>
     *
     * @param value The bytes for name to set.
     *
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      natureCase_ = 2;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string type = 3;</code>
     *
     * @param value The type to set.
     *
     * @return This builder for chaining.
     */
    public Builder setType(
        String value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      natureCase_ = 3;
      nature_ = value;
      onChanged();
      return this;
    }


    /**
     * <code>string type = 3;</code>
     *
     * @param value The bytes for type to set.
     *
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value
    ) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      natureCase_ = 3;
      nature_ = value;
      onChanged();
      return this;
    }


    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields
    ) {
      return super.setUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:beantest.MessageWithOneOf)
  }



  ;


  public static MessageWithOneOf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }


  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return Example.internal_static_beantest_MessageWithOneOf_descriptor;
  }


  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }


  public static Builder newBuilder(MessageWithOneOf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }


  public static MessageWithOneOf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }


  public static MessageWithOneOf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }


  public static MessageWithOneOf parseFrom(
      java.nio.ByteBuffer data
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static MessageWithOneOf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static MessageWithOneOf parseFrom(
      com.google.protobuf.ByteString data
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static MessageWithOneOf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static MessageWithOneOf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static MessageWithOneOf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static MessageWithOneOf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }


  public static MessageWithOneOf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }


  public static MessageWithOneOf parseFrom(
      com.google.protobuf.CodedInputStream input
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }


  public static MessageWithOneOf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }


  public static com.google.protobuf.Parser<MessageWithOneOf> parser() {
    return PARSER;
  }

  static {
    DEFAULT_INSTANCE = new MessageWithOneOf();
  }

  private byte memoizedIsInitialized = -1;

  private int natureCase_ = 0;

  @SuppressWarnings("serial")
  private Object nature_;


  // Use MessageWithOneOf.newBuilder() to construct.
  private MessageWithOneOf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }


  private MessageWithOneOf() {
  }


  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof MessageWithOneOf)) {
      return super.equals(obj);
    }
    MessageWithOneOf other = (MessageWithOneOf) obj;

    if (!getNatureCase().equals(other.getNatureCase())) {
      return false;
    }
    switch (natureCase_) {
      case 1:
        if (!getLabel()
            .equals(other.getLabel())) {
          return false;
        }
        break;
      case 2:
        if (!getName()
            .equals(other.getName())) {
          return false;
        }
        break;
      case 3:
        if (!getType()
            .equals(other.getType())) {
          return false;
        }
        break;
      case 4:
        if (!getKind()
            .equals(other.getKind())) {
          return false;
        }
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }


  @Override
  public MessageWithOneOf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }


  /**
   * <code>string kind = 4;</code>
   *
   * @return The kind.
   */
  public String getKind() {
    Object ref = "";
    if (natureCase_ == 4) {
      ref = nature_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (natureCase_ == 4) {
        nature_ = s;
      }
      return s;
    }
  }


  /**
   * <code>string kind = 4;</code>
   *
   * @return The bytes for kind.
   */
  public com.google.protobuf.ByteString
  getKindBytes() {
    Object ref = "";
    if (natureCase_ == 4) {
      ref = nature_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (natureCase_ == 4) {
        nature_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }


  /**
   * <code>string label = 1;</code>
   *
   * @return The label.
   */
  public String getLabel() {
    Object ref = "";
    if (natureCase_ == 1) {
      ref = nature_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (natureCase_ == 1) {
        nature_ = s;
      }
      return s;
    }
  }


  /**
   * <code>string label = 1;</code>
   *
   * @return The bytes for label.
   */
  public com.google.protobuf.ByteString
  getLabelBytes() {
    Object ref = "";
    if (natureCase_ == 1) {
      ref = nature_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (natureCase_ == 1) {
        nature_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }


  /**
   * <code>string name = 2;</code>
   *
   * @return The name.
   */
  public String getName() {
    Object ref = "";
    if (natureCase_ == 2) {
      ref = nature_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (natureCase_ == 2) {
        nature_ = s;
      }
      return s;
    }
  }


  /**
   * <code>string name = 2;</code>
   *
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
  getNameBytes() {
    Object ref = "";
    if (natureCase_ == 2) {
      ref = nature_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (natureCase_ == 2) {
        nature_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }


  public NatureCase
  getNatureCase() {
    return NatureCase.forNumber(
        natureCase_);
  }


  @Override
  public com.google.protobuf.Parser<MessageWithOneOf> getParserForType() {
    return PARSER;
  }


  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (natureCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nature_);
    }
    if (natureCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nature_);
    }
    if (natureCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nature_);
    }
    if (natureCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nature_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }


  /**
   * <code>string type = 3;</code>
   *
   * @return The type.
   */
  public String getType() {
    Object ref = "";
    if (natureCase_ == 3) {
      ref = nature_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (natureCase_ == 3) {
        nature_ = s;
      }
      return s;
    }
  }


  /**
   * <code>string type = 3;</code>
   *
   * @return The bytes for type.
   */
  public com.google.protobuf.ByteString
  getTypeBytes() {
    Object ref = "";
    if (natureCase_ == 3) {
      ref = nature_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (natureCase_ == 3) {
        nature_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }


  /**
   * <code>string kind = 4;</code>
   *
   * @return Whether the kind field is set.
   */
  public boolean hasKind() {
    return natureCase_ == 4;
  }


  /**
   * <code>string label = 1;</code>
   *
   * @return Whether the label field is set.
   */
  public boolean hasLabel() {
    return natureCase_ == 1;
  }


  /**
   * <code>string name = 2;</code>
   *
   * @return Whether the name field is set.
   */
  public boolean hasName() {
    return natureCase_ == 2;
  }


  /**
   * <code>string type = 3;</code>
   *
   * @return Whether the type field is set.
   */
  public boolean hasType() {
    return natureCase_ == 3;
  }


  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (natureCase_) {
      case 1:
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
        break;
      case 2:
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        break;
      case 3:
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
        break;
      case 4:
        hash = (37 * hash) + KIND_FIELD_NUMBER;
        hash = (53 * hash) + getKind().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }


  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return Example.internal_static_beantest_MessageWithOneOf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MessageWithOneOf.class, Builder.class);
  }


  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }


  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }


  @Override
  protected Builder newBuilderForType(
      BuilderParent parent
  ) {
    Builder builder = new Builder(parent);
    return builder;
  }


  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused
  ) {
    return new MessageWithOneOf();
  }


  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }


  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (natureCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nature_);
    }
    if (natureCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nature_);
    }
    if (natureCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nature_);
    }
    if (natureCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nature_);
    }
    getUnknownFields().writeTo(output);
  }

}

