// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

public interface NestedMessageOrBuilder extends
                                        // @@protoc_insertion_point(interface_extends:beantest.NestedMessage)
                                            com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   *
   * @return The nested.
   */
  NestedMessage getNested();

  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   */
  NestedMessageOrBuilder getNestedOrBuilder();

  /**
   * <code>int32 value = 1;</code>
   *
   * @return The value.
   */
  int getValue();

  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   *
   * @return Whether the nested field is set.
   */
  boolean hasNested();

}
