// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.pippsford.beantester.sample.protobuf;

/**
 * Protobuf type {@code beantest.NestedMessage}
 */
public final class NestedMessage extends
                                 com.google.protobuf.GeneratedMessageV3 implements
                                                                        // @@protoc_insertion_point(message_implements:beantest.NestedMessage)
                                                                            NestedMessageOrBuilder {

  public static final int NESTED_FIELD_NUMBER = 2;

  public static final int VALUE_FIELD_NUMBER = 1;

  // @@protoc_insertion_point(class_scope:beantest.NestedMessage)
  private static final NestedMessage DEFAULT_INSTANCE;

  private static final com.google.protobuf.Parser<NestedMessage>
      PARSER = new com.google.protobuf.AbstractParser<NestedMessage>() {
    @Override
    public NestedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    )
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  private static final long serialVersionUID = 0L;



  /**
   * Protobuf type {@code beantest.NestedMessage}
   */
  public static final class Builder extends
                                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                            // @@protoc_insertion_point(builder_implements:beantest.NestedMessage)
                                                                                                NestedMessageOrBuilder {

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Example.internal_static_beantest_NestedMessage_descriptor;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        NestedMessage, Builder, NestedMessageOrBuilder> nestedBuilder_;

    private NestedMessage nested_;

    private int value_;


    // Construct using com.pippsford.beantester.protobuf.NestedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }


    private Builder(
        BuilderParent parent
    ) {
      super(parent);
      maybeForceBuilderInitialization();
    }


    @Override
    public NestedMessage build() {
      NestedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }


    @Override
    public NestedMessage buildPartial() {
      NestedMessage result = new NestedMessage(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }


    private void buildPartial0(NestedMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.value_ = value_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nested_ = nestedBuilder_ == null
            ? nested_
            : nestedBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }


    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      value_ = 0;
      nested_ = null;
      if (nestedBuilder_ != null) {
        nestedBuilder_.dispose();
        nestedBuilder_ = null;
      }
      return this;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public Builder clearNested() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nested_ = null;
      if (nestedBuilder_ != null) {
        nestedBuilder_.dispose();
        nestedBuilder_ = null;
      }
      onChanged();
      return this;
    }


    /**
     * <code>int32 value = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = 0;
      onChanged();
      return this;
    }


    @Override
    public NestedMessage getDefaultInstanceForType() {
      return NestedMessage.getDefaultInstance();
    }


    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return Example.internal_static_beantest_NestedMessage_descriptor;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     *
     * @return The nested.
     */
    public NestedMessage getNested() {
      if (nestedBuilder_ == null) {
        return nested_ == null ? NestedMessage.getDefaultInstance() : nested_;
      } else {
        return nestedBuilder_.getMessage();
      }
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public Builder getNestedBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getNestedFieldBuilder().getBuilder();
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NestedMessage, Builder, NestedMessageOrBuilder>
    getNestedFieldBuilder() {
      if (nestedBuilder_ == null) {
        nestedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NestedMessage, Builder, NestedMessageOrBuilder>(
            getNested(),
            getParentForChildren(),
            isClean()
        );
        nested_ = null;
      }
      return nestedBuilder_;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public NestedMessageOrBuilder getNestedOrBuilder() {
      if (nestedBuilder_ != null) {
        return nestedBuilder_.getMessageOrBuilder();
      } else {
        return nested_ == null ?
            NestedMessage.getDefaultInstance() : nested_;
      }
    }


    /**
     * <code>int32 value = 1;</code>
     *
     * @return The value.
     */
    @Override
    public int getValue() {
      return value_;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     *
     * @return Whether the nested field is set.
     */
    public boolean hasNested() {
      return ((bitField0_ & 0x00000002) != 0);
    }


    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Example.internal_static_beantest_NestedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NestedMessage.class, Builder.class);
    }


    @Override
    public final boolean isInitialized() {
      return true;
    }


    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getNestedFieldBuilder();
      }
    }


    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NestedMessage) {
        return mergeFrom((NestedMessage) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }


    public Builder mergeFrom(NestedMessage other) {
      if (other == NestedMessage.getDefaultInstance()) {
        return this;
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      if (other.hasNested()) {
        mergeNested(other.getNested());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }


    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry
    )
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              value_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getNestedFieldBuilder().getBuilder(),
                  extensionRegistry
              );
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public Builder mergeNested(NestedMessage value) {
      if (nestedBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            nested_ != null &&
            nested_ != NestedMessage.getDefaultInstance()) {
          getNestedBuilder().mergeFrom(value);
        } else {
          nested_ = value;
        }
      } else {
        nestedBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }


    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields
    ) {
      return super.mergeUnknownFields(unknownFields);
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public Builder setNested(NestedMessage value) {
      if (nestedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nested_ = value;
      } else {
        nestedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }


    /**
     * <code>optional .beantest.NestedMessage nested = 2;</code>
     */
    public Builder setNested(
        Builder builderForValue
    ) {
      if (nestedBuilder_ == null) {
        nested_ = builderForValue.build();
      } else {
        nestedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }


    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields
    ) {
      return super.setUnknownFields(unknownFields);
    }


    /**
     * <code>int32 value = 1;</code>
     *
     * @param value The value to set.
     *
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {

      value_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:beantest.NestedMessage)
  }


  public static NestedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }


  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return Example.internal_static_beantest_NestedMessage_descriptor;
  }


  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }


  public static Builder newBuilder(NestedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }


  public static NestedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }


  public static NestedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }


  public static NestedMessage parseFrom(
      java.nio.ByteBuffer data
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static NestedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static NestedMessage parseFrom(
      com.google.protobuf.ByteString data
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static NestedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static NestedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }


  public static NestedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }


  public static NestedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }


  public static NestedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }


  public static NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }


  public static NestedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry
  )
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }


  public static com.google.protobuf.Parser<NestedMessage> parser() {
    return PARSER;
  }

  static {
    DEFAULT_INSTANCE = new NestedMessage();
  }

  private int bitField0_;

  private byte memoizedIsInitialized = -1;

  private NestedMessage nested_;

  private int value_ = 0;


  // Use NestedMessage.newBuilder() to construct.
  private NestedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }


  private NestedMessage() {
  }


  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof NestedMessage)) {
      return super.equals(obj);
    }
    NestedMessage other = (NestedMessage) obj;

    if (getValue()
        != other.getValue()) {
      return false;
    }
    if (hasNested() != other.hasNested()) {
      return false;
    }
    if (hasNested()) {
      if (!getNested()
          .equals(other.getNested())) {
        return false;
      }
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }


  @Override
  public NestedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }


  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   *
   * @return The nested.
   */
  @Override
  public NestedMessage getNested() {
    return nested_ == null ? NestedMessage.getDefaultInstance() : nested_;
  }


  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   */
  @Override
  public NestedMessageOrBuilder getNestedOrBuilder() {
    return nested_ == null ? NestedMessage.getDefaultInstance() : nested_;
  }


  @Override
  public com.google.protobuf.Parser<NestedMessage> getParserForType() {
    return PARSER;
  }


  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNested());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }


  /**
   * <code>int32 value = 1;</code>
   *
   * @return The value.
   */
  @Override
  public int getValue() {
    return value_;
  }


  /**
   * <code>optional .beantest.NestedMessage nested = 2;</code>
   *
   * @return Whether the nested field is set.
   */
  @Override
  public boolean hasNested() {
    return ((bitField0_ & 0x00000001) != 0);
  }


  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    if (hasNested()) {
      hash = (37 * hash) + NESTED_FIELD_NUMBER;
      hash = (53 * hash) + getNested().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }


  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return Example.internal_static_beantest_NestedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NestedMessage.class, Builder.class);
  }


  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }


  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }


  @Override
  protected Builder newBuilderForType(
      BuilderParent parent
  ) {
    Builder builder = new Builder(parent);
    return builder;
  }


  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused
  ) {
    return new NestedMessage();
  }


  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }


  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (value_ != 0) {
      output.writeInt32(1, value_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getNested());
    }
    getUnknownFields().writeTo(output);
  }

}

